const {
  GOOGLE_OAUTH_CLIENT_ID,
  GOOGLE_OAUTH_CLIENT_SECRET,
  URL_REDIRECT_OAUTH,
  JWT_REFRESH_SECRET,
  JWT_AUTH_SECRET,
  JWT_AUTH_EXP,
  JWT_REFRESH_EXP,
} = process.env

const globalOAuthValues = {
  GOOGLE_OAUTH_CLIENT_ID,
  GOOGLE_OAUTH_CLIENT_SECRET,
  URL_REDIRECT_OAUTH,
  JWT_REFRESH_SECRET,
  JWT_AUTH_SECRET,
  JWT_AUTH_EXP,
  JWT_REFRESH_EXP,
}
export default globalOAuthValues
